#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUTPUT_DIR="${1:-${REPO_ROOT}/docs/chef360-cli-help}"
CLIS=(
  chef-platform-auth-cli
  chef-node-management-cli
  chef-courier-cli
  chef-node-enrollment-cli
  chef-dsm-cli
  chef-import-cli
)

sanitize_help() {
  local text="$1"
  local line

  text="${text//-----BEGIN RSA PRIVATE KEY-----/[private key omitted]}"
  text="${text//-----END RSA PRIVATE KEY-----/[private key omitted]}"
  text="${text//-----BEGIN OPENSSH PRIVATE KEY-----/[private key omitted]}"
  text="${text//-----END OPENSSH PRIVATE KEY-----/[private key omitted]}"
  while IFS= read -r line || [[ -n "${line}" ]]; do
    line="${line%"${line##*[![:space:]]}"}"
    printf '%s\n' "${line}"
  done <<< "${text}"
}

capture_command() {
  local cli="$1"
  local output_file="$2"
  shift 2
  local -a path=("$@")
  local -a children=()
  local raw_help_output
  local help_output
  local display="${cli}"
  local line
  local child
  local in_commands=false

  if (( ${#path[@]} > 0 )); then
    display+=" ${path[*]}"
  fi

  if ! raw_help_output="$("${cli}" "${path[@]}" --help 2>&1)"; then
    printf 'WARNING: unable to capture `%s --help`\n' "${display}" >&2
    return
  fi
  help_output="$(sanitize_help "${raw_help_output}")"

  {
    printf '## `%s`\n\n' "${display}"
    printf '```text\n%s\n```\n\n' "${help_output}"
  } >> "${output_file}"

  while IFS= read -r line; do
    if [[ "${line}" == "Available Commands:" ]]; then
      in_commands=true
      continue
    fi
    if [[ "${in_commands}" == true && ( "${line}" == "Flags:"* || "${line}" == "Additional help topics:"* || "${line}" == "Use \""* ) ]]; then
      break
    fi
    if [[ "${in_commands}" == true && "${line}" =~ ^[[:space:]]+([^[:space:]]+)[[:space:]]+ ]]; then
      children+=("${BASH_REMATCH[1]}")
    fi
  done <<< "${raw_help_output}"

  for child in "${children[@]}"; do
    case "${child}" in
      completion|help)
        continue
        ;;
    esac
    capture_command "${cli}" "${output_file}" "${path[@]}" "${child}"
  done
}

mkdir -p "${OUTPUT_DIR}"

for cli in "${CLIS[@]}"; do
  if ! command -v "${cli}" >/dev/null 2>&1; then
    printf 'WARNING: %s is not installed; skipping it.\n' "${cli}" >&2
    continue
  fi

  output_file="${OUTPUT_DIR}/${cli}.md"
  version_output="$("${cli}" version 2>&1 || true)"
  version_output="$(sanitize_help "${version_output}")"

  {
    printf '# `%s` Local Command Reference\n\n' "${cli}"
    printf '> Generated by `scripts/content/capture-chef360-cli-help.sh` from the locally installed CLI. '
    printf 'Regenerate after upgrading Chef 360 CLI packages.\n\n'
    printf '## Captured Version\n\n'
    printf '```text\n%s\n```\n\n' "${version_output}"
  } > "${output_file}"

  capture_command "${cli}" "${output_file}"
  file_content="$(<"${output_file}")"
  printf '%s\n' "${file_content}" > "${output_file}"
  printf 'Captured %s\n' "${output_file}"
done
