#!/usr/bin/env bash

KVM_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${KVM_SCRIPT_DIR}/../.." && pwd)"
KVM_STATE_FILE="${KVM_CHEF360_STATE_FILE:-${PROJECT_ROOT}/config/kvm-chef360.env}"

# Capture explicitly-set source variables before the state file is sourced, so
# an explicit environment override always wins over the state file and the
# source cache.
SOURCE_ENV_UBUNTU_ISO="${UBUNTU_ISO+x}";     SOURCE_ENV_UBUNTU_ISO_VALUE="${UBUNTU_ISO-}"
SOURCE_ENV_CHEF360_INSTALLER_SOURCE="${CHEF360_INSTALLER_SOURCE+x}"; SOURCE_ENV_CHEF360_INSTALLER_SOURCE_VALUE="${CHEF360_INSTALLER_SOURCE-}"
SOURCE_ENV_CHEF360_LICENSE_SOURCE="${CHEF360_LICENSE_SOURCE+x}"; SOURCE_ENV_CHEF360_LICENSE_SOURCE_VALUE="${CHEF360_LICENSE_SOURCE-}"
SOURCE_ENV_CHEF360_TLS_CERT="${CHEF360_TLS_CERT+x}"; SOURCE_ENV_CHEF360_TLS_CERT_VALUE="${CHEF360_TLS_CERT-}"
SOURCE_ENV_CHEF360_TLS_KEY="${CHEF360_TLS_KEY+x}"; SOURCE_ENV_CHEF360_TLS_KEY_VALUE="${CHEF360_TLS_KEY-}"
SOURCE_ENV_CHEF360_TLS_CHAIN="${CHEF360_TLS_CHAIN+x}"; SOURCE_ENV_CHEF360_TLS_CHAIN_VALUE="${CHEF360_TLS_CHAIN-}"
SOURCE_ENV_CHEF360_ISSUING_CA="${CHEF360_ISSUING_CA+x}"; SOURCE_ENV_CHEF360_ISSUING_CA_VALUE="${CHEF360_ISSUING_CA-}"
SOURCE_ENV_CHEF360_ROOT_CA="${CHEF360_ROOT_CA+x}"; SOURCE_ENV_CHEF360_ROOT_CA_VALUE="${CHEF360_ROOT_CA-}"

# Record which path variables were explicitly set by the caller before the state
# file is sourced, so the plan can override VM_NAME without clobbering caller
# overrides. The state file itself is regenerated by the build and is treated as
# transient: offending values (e.g. a stale KVM_WORK_DIR) are recomputed.
SOURCE_ENV_OS_DISK="${OS_DISK+x}"
SOURCE_ENV_DATA_DISK="${DATA_DISK+x}"
SOURCE_ENV_KVM_WORK_DIR="${KVM_WORK_DIR+x}"
SOURCE_ENV_SEED_ISO="${SEED_ISO+x}"
SOURCE_ENV_INSTALL_KERNEL="${INSTALL_KERNEL+x}"
SOURCE_ENV_INSTALL_INITRD="${INSTALL_INITRD+x}"
SOURCE_ENV_LIBVIRT_SEED_ISO="${LIBVIRT_SEED_ISO+x}"
SOURCE_ENV_LIBVIRT_INSTALL_KERNEL="${LIBVIRT_INSTALL_KERNEL+x}"
SOURCE_ENV_LIBVIRT_INSTALL_INITRD="${LIBVIRT_INSTALL_INITRD+x}"
SOURCE_ENV_CHEF360_CONFIG_FILE="${CHEF360_CONFIG_FILE+x}"
SOURCE_ENV_CHEF360_SECRETS_FILE="${CHEF360_SECRETS_FILE+x}"
SOURCE_ENV_CHEF360_STAGE_DIR="${CHEF360_STAGE_DIR+x}"
SOURCE_ENV_CHEF360_STAGE_MANIFEST="${CHEF360_STAGE_MANIFEST+x}"

if [[ -f "${KVM_STATE_FILE}" ]]; then
  # The state file is generated by this project and contains non-secret paths and VM metadata.
  # shellcheck disable=SC1090
  source "${KVM_STATE_FILE}"
fi

# Restore explicit environment values that the state file would otherwise shadow.
[[ -z "${SOURCE_ENV_UBUNTU_ISO}" ]] || UBUNTU_ISO="${SOURCE_ENV_UBUNTU_ISO_VALUE}"
[[ -z "${SOURCE_ENV_CHEF360_INSTALLER_SOURCE}" ]] || CHEF360_INSTALLER_SOURCE="${SOURCE_ENV_CHEF360_INSTALLER_SOURCE_VALUE}"
[[ -z "${SOURCE_ENV_CHEF360_LICENSE_SOURCE}" ]] || CHEF360_LICENSE_SOURCE="${SOURCE_ENV_CHEF360_LICENSE_SOURCE_VALUE}"
[[ -z "${SOURCE_ENV_CHEF360_TLS_CERT}" ]] || CHEF360_TLS_CERT="${SOURCE_ENV_CHEF360_TLS_CERT_VALUE}"
[[ -z "${SOURCE_ENV_CHEF360_TLS_KEY}" ]] || CHEF360_TLS_KEY="${SOURCE_ENV_CHEF360_TLS_KEY_VALUE}"
[[ -z "${SOURCE_ENV_CHEF360_TLS_CHAIN}" ]] || CHEF360_TLS_CHAIN="${SOURCE_ENV_CHEF360_TLS_CHAIN_VALUE}"
[[ -z "${SOURCE_ENV_CHEF360_ISSUING_CA}" ]] || CHEF360_ISSUING_CA="${SOURCE_ENV_CHEF360_ISSUING_CA_VALUE}"
[[ -z "${SOURCE_ENV_CHEF360_ROOT_CA}" ]] || CHEF360_ROOT_CA="${SOURCE_ENV_CHEF360_ROOT_CA_VALUE}"

# Optional local source cache. When set to a directory that already contains the
# matching artifact, builds prefer it over the default /install paths. Set
# KVM_SOURCE_DIR to point at a maintained cache such as ~/repos/sources.
KVM_SOURCE_DIR="${KVM_SOURCE_DIR:-}"

VM_NAME="${VM_NAME:-20_chef360}"
VM_HOSTNAME="${VM_HOSTNAME:-chef360.demo.lab}"
VM_SHORT_HOSTNAME="${VM_SHORT_HOSTNAME:-chef360}"
VM_IP="${VM_IP:-10.0.0.20}"
VM_PREFIX="${VM_PREFIX:-24}"
VM_GATEWAY="${VM_GATEWAY:-10.0.0.2}"
VM_DNS="${VM_DNS:-10.0.0.1}"
KVM_HOST_IP="${KVM_HOST_IP:-10.0.0.1}"
KVM_HOST_FQDN="${KVM_HOST_FQDN:-fury.demo.lab}"
AUTOMATE_IP="${AUTOMATE_IP:-10.0.0.21}"
AUTOMATE_FQDN="${AUTOMATE_FQDN:-automate.demo.lab}"
NODE1_IP="${NODE1_IP:-10.0.0.23}"
NODE1_FQDN="${NODE1_FQDN:-node1.demo.lab}"
NODE2_IP="${NODE2_IP:-10.0.0.24}"
NODE2_FQDN="${NODE2_FQDN:-node2.demo.lab}"
VM_NETWORK="${VM_NETWORK:-default}"
VM_MAC="${VM_MAC:-}"
VM_MEMORY_MIB="${VM_MEMORY_MIB:-32768}"
VM_VCPUS="${VM_VCPUS:-16}"
VM_CPU_SHARES="${VM_CPU_SHARES:-2048}"
VM_OS_DISK_GIB="${VM_OS_DISK_GIB:-50}"
VM_DATA_DISK_GIB="${VM_DATA_DISK_GIB:-250}"
VM_DISK_PREALLOCATION="${VM_DISK_PREALLOCATION:-falloc}"
VM_OS_DISK_SERIAL="${VM_OS_DISK_SERIAL:-CHEF360_OS}"
VM_DATA_DISK_SERIAL="${VM_DATA_DISK_SERIAL:-CHEF360_DATA}"
VM_USER="${VM_USER:-chef}"
SSH_PRIVATE_KEY="${SSH_PRIVATE_KEY:-${HOME}/.ssh/fury_rsa}"
SSH_PUBLIC_KEY="${SSH_PUBLIC_KEY:-${HOME}/.ssh/fury_rsa.pub}"
UBUNTU_ISO="${UBUNTU_ISO:-${HOME}/install/linux/ubuntu-24.04_server_amd64.iso}"
UBUNTU_MIRROR="${UBUNTU_MIRROR:-http://mirror.arizona.edu/ubuntu}"
LIBVIRT_POOL="${LIBVIRT_POOL:-default}"
LIBVIRT_URI="${LIBVIRT_URI:-qemu:///system}"
LIBVIRT_IMAGE_DIR="${LIBVIRT_IMAGE_DIR:-/var/lib/libvirt/images}"

# Naming convention: every artifact this project creates for a build is prefixed
# with the target VM name (${VM_NAME}), e.g. 30_chef360-PLAN.env and
# ~/certs/30_chef360.crt. This keeps per-build content self-describing and safe
# to share a directory with other builds. The plan file, seed ISO, install
# kernel/initrd, config, secrets, certs, staging tree, and disk images all follow
# the same <VM_NAME>- ... rule.
OS_DISK="${OS_DISK:-${LIBVIRT_IMAGE_DIR}/${VM_NAME}-os.qcow2}"
DATA_DISK="${DATA_DISK:-${LIBVIRT_IMAGE_DIR}/${VM_NAME}-data.qcow2}"
KVM_WORK_DIR="${KVM_WORK_DIR:-${PROJECT_ROOT}/.kvm/${VM_NAME}}"
SEED_ISO="${SEED_ISO:-${KVM_WORK_DIR}/${VM_NAME}-seed.iso}"
INSTALL_KERNEL="${INSTALL_KERNEL:-${KVM_WORK_DIR}/${VM_NAME}-vmlinuz}"
INSTALL_INITRD="${INSTALL_INITRD:-${KVM_WORK_DIR}/${VM_NAME}-initrd}"
LIBVIRT_SEED_ISO="${LIBVIRT_SEED_ISO:-${LIBVIRT_IMAGE_DIR}/${VM_NAME}-seed.iso}"
LIBVIRT_INSTALL_KERNEL="${LIBVIRT_INSTALL_KERNEL:-${LIBVIRT_IMAGE_DIR}/${VM_NAME}-vmlinuz}"
LIBVIRT_INSTALL_INITRD="${LIBVIRT_INSTALL_INITRD:-${LIBVIRT_IMAGE_DIR}/${VM_NAME}-initrd}"
CHEF360_CONFIG_TEMPLATE="${CHEF360_CONFIG_TEMPLATE:-${PROJECT_ROOT}/knowledge-set/chef360-1.7.3/examples/kots-config.yaml}"
CHEF360_CONFIG_FILE="${CHEF360_CONFIG_FILE:-${KVM_WORK_DIR}/${VM_NAME}-config.yaml}"
CHEF360_SECRETS_FILE="${CHEF360_SECRETS_FILE:-${KVM_WORK_DIR}/${VM_NAME}-secrets.env}"
CHEF360_TLS_CERT="${CHEF360_TLS_CERT:-${HOME}/certs/${VM_NAME}.crt}"
CHEF360_TLS_KEY="${CHEF360_TLS_KEY:-${HOME}/certs/${VM_NAME}.key}"
CHEF360_TLS_CHAIN="${CHEF360_TLS_CHAIN:-${HOME}/certs/${VM_NAME}_chain.crt}"
CHEF360_ISSUING_CA="${CHEF360_ISSUING_CA:-${HOME}/certs/${VM_NAME}_ica.crt}"
CHEF360_ROOT_CA="${CHEF360_ROOT_CA:-${HOME}/certs/${VM_NAME}_rca.crt}"
CHEF360_INSTALLER_SOURCE="${CHEF360_INSTALLER_SOURCE:-${HOME}/install/chef/chef-360/1.7/chef-360}"
CHEF360_LICENSE_SOURCE="${CHEF360_LICENSE_SOURCE:-${HOME}/install/chef/chef-360/1.7/license.yaml}"
CHEF360_STAGE_DIR="${CHEF360_STAGE_DIR:-${KVM_WORK_DIR}/${VM_NAME}-stage}"
CHEF360_STAGE_MANIFEST="${CHEF360_STAGE_MANIFEST:-${CHEF360_STAGE_DIR}/${VM_NAME}-MANIFEST.txt}"

CHEF360_IGNORE_APP_PREFLIGHTS="${CHEF360_IGNORE_APP_PREFLIGHTS:-1}"
CHEF360_ADMIN_CONSOLE_PASSWORD="${CHEF360_ADMIN_CONSOLE_PASSWORD:-devsecops}"
VM_INITIAL_PASSWORD="${VM_INITIAL_PASSWORD:-devsecops}"
PROVISION_METHOD="${PROVISION_METHOD:-os_iso}"
CHEF360_CLONE_SOURCE="${CHEF360_CLONE_SOURCE:-}"

# Application-backend decisions kept fixed for the lab. The plan records them
# as a reproducible snapshot; they are not prompted during plan creation.
SMTP_OPTION="${SMTP_OPTION:-mailpit}"
STORAGE_OPTION="${STORAGE_OPTION:-minio}"
OPENSEARCH_OPTION="${OPENSEARCH_OPTION:-embedded}"
POSTGRESQL_OPTION="${POSTGRESQL_OPTION:-cnpg}"
TEMPORAL_OPTION="${TEMPORAL_OPTION:-onprem}"
CNPG_BACKUP_ENABLED="${CNPG_BACKUP_ENABLED:-0}"
CLUSTER_TOPOLOGY="${CLUSTER_TOPOLOGY:-hyperconverged-nonha}"
PREFLIGHT_STRICT_MODE="${PREFLIGHT_STRICT_MODE:-0}"

# Tenant and endpoint configuration shared by the config generator, the plan,
# and the deployment validators. Moving these defaults here keeps one source
# of truth; generate-chef360-config.sh therefore reads them from the env.
TENANT_NAME="${TENANT_NAME:-demolab}"
TENANT_TLD="${TENANT_TLD:-demo.lab}"
TENANT_SUBDOMAIN="${TENANT_SUBDOMAIN:-${VM_SHORT_HOSTNAME}}"
TENANT_OU="${TENANT_OU:-lab}"
TENANT_OU_DESCRIPTION="${TENANT_OU_DESCRIPTION:-Lab organization}"
TENANT_ADMIN_FIRST_NAME="${TENANT_ADMIN_FIRST_NAME:-Chef}"
TENANT_ADMIN_LAST_NAME="${TENANT_ADMIN_LAST_NAME:-Admin}"
TENANT_ADMIN_EMAIL="${TENANT_ADMIN_EMAIL:-admin@demo.lab}"
GATEWAY_NODEPORT="${GATEWAY_NODEPORT:-31000}"
MAILPIT_NODEPORT="${MAILPIT_NODEPORT:-31101}"
RABBITMQ_AMQP_NODEPORT="${RABBITMQ_AMQP_NODEPORT:-31050}"

# Bind a build-specific project plan. create-chef360-plan.sh materializes a
# reviewed and approved plan into ${CHEF360_PLAN_FILE} for the effective
# VM_NAME. When present its values override the defaults above and drive the
# VM build (deploy-chef360-vm.sh), the Chef 360 install (install-chef360.sh),
# and the generated config.yaml.
CHEF360_PLAN_FILE="${CHEF360_PLAN_FILE:-${KVM_WORK_DIR}/${VM_NAME}-PLAN.env}"
if [[ -f "${CHEF360_PLAN_FILE}" ]]; then
  # The plan file is generated by this project from reviewed, approved input.
  # shellcheck disable=SC1090
  source "${CHEF360_PLAN_FILE}"
  # An "existing" plan records the live disk paths; keep them after recompute.
  grep -Eq '^OS_DISK=' "${CHEF360_PLAN_FILE}" && PLAN_OS_DISK=set
  grep -Eq '^DATA_DISK=' "${CHEF360_PLAN_FILE}" && PLAN_DATA_DISK=set
fi

# The plan may have changed VM_NAME. Recompute any path variables that were
# derived from the default VM_NAME and were not explicitly set by the caller
# or materialized in the plan file.
[[ -n "${SOURCE_ENV_OS_DISK}" || "${PLAN_OS_DISK:-}" == "set" ]] || OS_DISK="${LIBVIRT_IMAGE_DIR}/${VM_NAME}-os.qcow2"
[[ -n "${SOURCE_ENV_DATA_DISK}" || "${PLAN_DATA_DISK:-}" == "set" ]] || DATA_DISK="${LIBVIRT_IMAGE_DIR}/${VM_NAME}-data.qcow2"
[[ -n "${SOURCE_ENV_KVM_WORK_DIR}" ]] || KVM_WORK_DIR="${PROJECT_ROOT}/.kvm/${VM_NAME}"
[[ -n "${SOURCE_ENV_SEED_ISO}" ]] || SEED_ISO="${KVM_WORK_DIR}/${VM_NAME}-seed.iso"
[[ -n "${SOURCE_ENV_INSTALL_KERNEL}" ]] || INSTALL_KERNEL="${KVM_WORK_DIR}/${VM_NAME}-vmlinuz"
[[ -n "${SOURCE_ENV_INSTALL_INITRD}" ]] || INSTALL_INITRD="${KVM_WORK_DIR}/${VM_NAME}-initrd"
[[ -n "${SOURCE_ENV_LIBVIRT_SEED_ISO}" ]] || LIBVIRT_SEED_ISO="${LIBVIRT_IMAGE_DIR}/${VM_NAME}-seed.iso"
[[ -n "${SOURCE_ENV_LIBVIRT_INSTALL_KERNEL}" ]] || LIBVIRT_INSTALL_KERNEL="${LIBVIRT_IMAGE_DIR}/${VM_NAME}-vmlinuz"
[[ -n "${SOURCE_ENV_LIBVIRT_INSTALL_INITRD}" ]] || LIBVIRT_INSTALL_INITRD="${LIBVIRT_IMAGE_DIR}/${VM_NAME}-initrd"
[[ -n "${SOURCE_ENV_CHEF360_CONFIG_FILE}" ]] || CHEF360_CONFIG_FILE="${KVM_WORK_DIR}/${VM_NAME}-config.yaml"
[[ -n "${SOURCE_ENV_CHEF360_SECRETS_FILE}" ]] || CHEF360_SECRETS_FILE="${KVM_WORK_DIR}/${VM_NAME}-secrets.env"
[[ -n "${SOURCE_ENV_CHEF360_STAGE_DIR}" ]] || CHEF360_STAGE_DIR="${KVM_WORK_DIR}/${VM_NAME}-stage"
[[ -n "${SOURCE_ENV_CHEF360_STAGE_MANIFEST}" ]] || CHEF360_STAGE_MANIFEST="${CHEF360_STAGE_DIR}/${VM_NAME}-MANIFEST.txt"

# Resolve an input artifact from the source cache when KVM_SOURCE_DIR names a
# directory that already holds the file. Explicit environment values win.
resolve_source() {
  local variable="$1" explicit_marker="$2" relative_path="$3" candidate
  [[ -n "${KVM_SOURCE_DIR}" ]] || return 0
  [[ -z "${explicit_marker}" ]] || return 0
  candidate="${KVM_SOURCE_DIR}/${relative_path}"
  [[ -e "${candidate}" ]] || return 0
  printf -v "${variable}" '%s' "${candidate}"
}

resolve_source UBUNTU_ISO "${SOURCE_ENV_UBUNTU_ISO}" "ubuntu/$(basename "${UBUNTU_ISO}")"
resolve_source CHEF360_INSTALLER_SOURCE "${SOURCE_ENV_CHEF360_INSTALLER_SOURCE}" "chef360/chef-360"
resolve_source CHEF360_LICENSE_SOURCE "${SOURCE_ENV_CHEF360_LICENSE_SOURCE}" "chef360/license.yaml"
resolve_source CHEF360_TLS_CERT "${SOURCE_ENV_CHEF360_TLS_CERT}" "chef360/tls/chef360-2.crt"
resolve_source CHEF360_TLS_KEY "${SOURCE_ENV_CHEF360_TLS_KEY}" "chef360/tls/chef360-2.key"
resolve_source CHEF360_TLS_CHAIN "${SOURCE_ENV_CHEF360_TLS_CHAIN}" "chef360/tls/chef360-2_chain.crt"
resolve_source CHEF360_ISSUING_CA "${SOURCE_ENV_CHEF360_ISSUING_CA}" "chef360/tls/chef360-2_ica.crt"
resolve_source CHEF360_ROOT_CA "${SOURCE_ENV_CHEF360_ROOT_CA}" "chef360/tls/chef360-2_rca.crt"

log_step() {
  printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"
}

fail() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "Required command not found: $1"
}

require_file() {
  [[ -f "$1" ]] || fail "Required file not found: $1"
}

virsh_system() {
  virsh --connect "${LIBVIRT_URI}" "$@"
}

vm_exists() {
  virsh_system dominfo "${VM_NAME}" >/dev/null 2>&1
}

save_kvm_state() {
  install -d -m 0700 "$(dirname "${KVM_STATE_FILE}")"
  cat >"${KVM_STATE_FILE}" <<EOF
VM_NAME=${VM_NAME}
VM_HOSTNAME=${VM_HOSTNAME}
VM_SHORT_HOSTNAME=${VM_SHORT_HOSTNAME}
VM_IP=${VM_IP}
VM_PREFIX=${VM_PREFIX}
VM_GATEWAY=${VM_GATEWAY}
VM_DNS=${VM_DNS}
KVM_HOST_IP=${KVM_HOST_IP}
KVM_HOST_FQDN=${KVM_HOST_FQDN}
AUTOMATE_IP=${AUTOMATE_IP}
AUTOMATE_FQDN=${AUTOMATE_FQDN}
NODE1_IP=${NODE1_IP}
NODE1_FQDN=${NODE1_FQDN}
NODE2_IP=${NODE2_IP}
NODE2_FQDN=${NODE2_FQDN}
VM_NETWORK=${VM_NETWORK}
VM_MAC=${VM_MAC}
VM_MEMORY_MIB=${VM_MEMORY_MIB}
VM_VCPUS=${VM_VCPUS}
VM_CPU_SHARES=${VM_CPU_SHARES}
VM_OS_DISK_GIB=${VM_OS_DISK_GIB}
VM_DATA_DISK_GIB=${VM_DATA_DISK_GIB}
VM_DISK_PREALLOCATION=${VM_DISK_PREALLOCATION}
VM_OS_DISK_SERIAL=${VM_OS_DISK_SERIAL}
VM_DATA_DISK_SERIAL=${VM_DATA_DISK_SERIAL}
VM_USER=${VM_USER}
SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
SSH_PUBLIC_KEY=${SSH_PUBLIC_KEY}
UBUNTU_ISO=${UBUNTU_ISO}
UBUNTU_MIRROR=${UBUNTU_MIRROR}
LIBVIRT_POOL=${LIBVIRT_POOL}
LIBVIRT_URI=${LIBVIRT_URI}
LIBVIRT_IMAGE_DIR=${LIBVIRT_IMAGE_DIR}
OS_DISK=${OS_DISK}
DATA_DISK=${DATA_DISK}
KVM_WORK_DIR=${KVM_WORK_DIR}
SEED_ISO=${SEED_ISO}
INSTALL_KERNEL=${INSTALL_KERNEL}
INSTALL_INITRD=${INSTALL_INITRD}
LIBVIRT_SEED_ISO=${LIBVIRT_SEED_ISO}
LIBVIRT_INSTALL_KERNEL=${LIBVIRT_INSTALL_KERNEL}
LIBVIRT_INSTALL_INITRD=${LIBVIRT_INSTALL_INITRD}
CHEF360_CONFIG_TEMPLATE=${CHEF360_CONFIG_TEMPLATE}
CHEF360_CONFIG_FILE=${CHEF360_CONFIG_FILE}
CHEF360_SECRETS_FILE=${CHEF360_SECRETS_FILE}
CHEF360_TLS_CERT=${CHEF360_TLS_CERT}
CHEF360_TLS_KEY=${CHEF360_TLS_KEY}
CHEF360_TLS_CHAIN=${CHEF360_TLS_CHAIN}
CHEF360_ISSUING_CA=${CHEF360_ISSUING_CA}
CHEF360_ROOT_CA=${CHEF360_ROOT_CA}
CHEF360_INSTALLER_SOURCE=${CHEF360_INSTALLER_SOURCE}
CHEF360_LICENSE_SOURCE=${CHEF360_LICENSE_SOURCE}
CHEF360_STAGE_DIR=${CHEF360_STAGE_DIR}
CHEF360_STAGE_MANIFEST=${CHEF360_STAGE_MANIFEST}
KVM_SOURCE_DIR=${KVM_SOURCE_DIR}
EOF
  chmod 0600 "${KVM_STATE_FILE}"
}

ssh_options() {
  printf '%s\n' \
    -o BatchMode=yes \
    -o ConnectTimeout=10 \
    -o StrictHostKeyChecking=accept-new \
    -i "${SSH_PRIVATE_KEY}"
}

# MAC addresses are never entered by the operator. OS-image builds derive a
# deterministic 52:54:00 MAC from VM_IP; clone builds must prove uniqueness and
# regenerate when the derived address is already in use. resolve_vm_mac()
# persists the chosen address into PLAN.env so generate, deploy, and validate
# agree within a build.
generate_os_vm_mac() {
  local oct
  IFS=. read -r _ oct2 oct3 oct4 <<<"${VM_IP}"
  printf '52:54:00:%02x:%02x:%02x' "${oct2}" "${oct3}" "${oct4}"
}

generate_random_vm_mac() {
  local a b c
  a="$(openssl rand -hex 1)"
  b="$(openssl rand -hex 1)"
  c="$(openssl rand -hex 1)"
  printf '52:54:00:%s:%s:%s' "${a}" "${b}" "${c}"
}

# Return 0 when any defined libvirt domain other than ${ignore} uses ${mac}.
vm_mac_in_use() {
  local mac="$1" ignore="${2:--}" domain current
  while IFS= read -r domain; do
    [[ -n "${domain}" ]] || continue
    [[ "${domain}" != "${ignore}" ]] || continue
    current="$(virsh_system dumpxml "${domain}" 2>/dev/null | sed -n "s/.*mac address='\([0-9a-fA-F:]*\)'.*/\1/p" | head -1)"
    [[ -n "${current}" && "${current}" == "${mac}" ]] && return 0
  done < <(virsh_system list --all --name 2>/dev/null)
  return 1
}

persist_plan_value() {
  local key="$1" value="$2" plan="${CHEF360_PLAN_FILE:-${KVM_WORK_DIR}/${VM_NAME}-PLAN.env}"
  [[ -f "${plan}" ]] || return 0
  if grep -q "^${key}=" "${plan}"; then
    sed -i "s|^${key}=.*|${key}=${value}|" "${plan}"
  else
    printf '%s=%s\n' "${key}" "${value}" >>"${plan}"
  fi
  chmod 0600 "${plan}"
}

resolve_vm_mac() {
  if [[ -z "${VM_MAC:-}" ]]; then
    VM_MAC="$(generate_os_vm_mac)"
  fi
  local tries=0
  while vm_mac_in_use "${VM_MAC}" "${VM_NAME}"; do
    log_step "MAC ${VM_MAC} is already in use; regenerating for ${VM_NAME}"
    VM_MAC="$(generate_random_vm_mac)"
    tries=$((tries + 1))
    (( tries < 32 )) || fail "Unable to allocate a unique MAC for ${VM_NAME}"
  done
  persist_plan_value VM_MAC "${VM_MAC}"
  log_step "Resolved guest MAC: ${VM_MAC}"
}
